# Generated by Django 3.1.2 on 2020-10-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='numero_do_cartao',
            field=models.IntegerField(default=2, verbose_name=10),
            preserve_default=False,
        ),
    ]
