# Generated by Django 3.1.2 on 2020-10-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_conta_numero_do_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='numero_do_cartao',
            field=models.IntegerField(verbose_name=16),
        ),
    ]
