# Generated by Django 3.1.2 on 2020-10-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_auto_20201023_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='numero_do_cartao',
            field=models.CharField(max_length=16),
        ),
    ]
