# Generated by Django 3.1.2 on 2020-10-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_auto_20201023_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='horario',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
